### ISSUE TITLE
Dependency for wxgtk

### ISSUE THREAD

**Issue by Padoup-Padoup** [DawesLab/Instruments#2]
Hi, 

First, thank for this piece of software, I finally managed to get the output of our Tek TDS2014C scope!

Just a minor point, that should be added to the README: wx is required to run `TekScopeGUI.py`.

I installed it with:

```{shell}
sudo apt-get install python-wxgtk3.0
```

Maybe it's worth mentioning in the README. 
Thank you,

**Comment by amcdawes** [comment]
Thanks, yes I'll make this change to the documentation. Glad you're finding this useful!
